name: Deploy xyzuan-api-v2 Development Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build & Push to GHCR Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Settle up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Declaring some Global Environtment vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "SHA=$(echo "$GITHUB_SHA" | head -c 7)" >> $GITHUB_ENV
          echo "ENV=dev" >> $GITHUB_ENV
          echo "PORT=3121" >> $GITHUB_ENV
          echo "BASE_URL=https://api.xyzuan.my.id/dev" >> $GITHUB_ENV
          echo "DOMAIN=xyzuan.my.id" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io/xyzuan" >> $GITHUB_ENV
          echo "IMAGE_NAME=xyzuan_api_v2" >> $GITHUB_ENV
          echo "DOCKERFILE=misc/Dockerfile" >> $GITHUB_ENV

      - name: Authenticating to GHCR realms
        run: echo "${{ secrets.GH_TOKEN }}" | docker login -u "${{ github.actor }}" ghcr.io --password-stdin

      - name: Treaty Build the Docker image
        run: |
          docker build \
          --build-arg PORT=${{ env.PORT }} \
          --build-arg NODE_ENV=${{ env.ENV }} \
          --build-arg BASE_URL=${{ env.BASE_URL }} \
          --build-arg DOMAIN=${{ env.DOMAIN }} \
          --build-arg PASSWORD_PEPPER=${{ secrets.PASSWORD_PEPPER }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL_DEV }} \
          --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          --build-arg GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
          --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
          --build-arg LINKEDIN_CLIENT_ID=${{ secrets.LINKEDIN_CLIENT_ID }} \
          --build-arg LINKEDIN_CLIENT_SECRET=${{ secrets.LINKEDIN_CLIENT_SECRET }} \
          --build-arg TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
          --build-arg TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
          --build-arg CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
          --build-arg CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
          --build-arg CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
          --build-arg MINIO_HOST=${{ secrets.MINIO_HOST }} \
          --build-arg MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }} \
          --build-arg MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }} \
          --build-arg MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }} \
          --build-arg AZURE_AI_URL=${{ secrets.AZURE_AI_URL }} \
          --build-arg AZURE_AI_API_KEY=${{ secrets.AZURE_AI_API_KEY }} \
          --build-arg AXIOM_SECRET_TOKEN=${{ secrets.AXIOM_SECRET_TOKEN }} \
          --build-arg AXIOM_DATASET=${{ secrets.AXIOM_DATASET }} \
          --build-arg REDIS_URL=${{ secrets.REDIS_URL_DEV }} \
          --build-arg REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
          -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }} -f ${{ env.DOCKERFILE }} .

      - name: Adding tags to the Images
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.SHA}}

      - name: Bring the Images to GHCR
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA }}

  serve:
    name: Serve Images in Server
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Connect to Twingate
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.TWINGATE_SERVICE_KEY }}

      - name: Authenticating to Eden Server realms
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

      - name: Declaring some Global Environtment vars
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "PORT=3121" >> $GITHUB_ENV
          echo "CT_NAME=xyzuan-api-v2-dev" >> $GITHUB_ENV
          echo "REGISTRY=ghcr.io/xyzuan" >> $GITHUB_ENV
          echo "IMAGE_NAME=xyzuan_api_v2" >> $GITHUB_ENV

      - name: Serve the Images
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          echo './nauzyxnet> Authenticating to GHCR realms...'
          echo "${{ secrets.GH_TOKEN }}" | docker login -u "${{ github.actor }}" ghcr.io --password-stdin

          echo './nauzyxnet> Pulling the latest image from GHCR...'
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}

          echo './nauzyxnet> Force Blowing the existing Docker Container...'
          docker stop ${{ env.CT_NAME }} || true
          docker rm -f ${{ env.CT_NAME }} || true

          echo './nauzyxnet> Creating the Docker Container...'
          docker run -d \
            --name ${{ env.CT_NAME }} \
            --restart unless-stopped \
            -p ${{ env.PORT }}:${{ env.PORT }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          EOF
