name: Build xyzuan-api-v2 Development Build

on:
  push:
    branches:
      - dev
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
          --build-arg PORT=3121 \
          --build-arg NODE_ENV=dev \
          --build-arg DOMAIN=xyzuan.my.id \
          --build-arg PASSWORD_PEPPER=${{ secrets.PASSWORD_PEPPER }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL_DEV }} \
          --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
          --build-arg GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
          --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
          --build-arg LINKEDIN_CLIENT_ID=${{ secrets.LINKEDIN_CLIENT_ID }} \
          --build-arg LINKEDIN_CLIENT_SECRET=${{ secrets.LINKEDIN_CLIENT_SECRET }} \
          --build-arg TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
          --build-arg TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
          --build-arg CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
          --build-arg CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
          --build-arg CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
          -t ghcr.io/xyzuan/xyzuan_api_v2:latest -f misc/Dockerfile.dev .

      - name: Tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/xyzuan/xyzuan_api_v2
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$(echo "${{ github.sha }}" | head -c 7)

      - name: Push Docker image
        run: |
          docker login --username xyzuan --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker push ghcr.io/xyzuan/xyzuan_api_v2:latest
          docker push ghcr.io/xyzuan/xyzuan_api_v2:$(echo "${{ github.sha }}" | head -c 7)
